import os
import logging
import json
import humanize

from wpamod.plugins.base.analysis_plugin import AnalysisPlugin


class SystemInformation(AnalysisPlugin):
    """
    Read the information generated by
    https://github.com/andresriancho/collector/blob/master/examples/w3af/get_sys_perf_data.py

    Which is stored in w3af-psutil.data
    """
    def analyze(self):
        psutil_file = os.path.join(self.input_directory, 'w3af-psutil.data')
        logging.debug('Analyzing "%s" psutil dump' % psutil_file)

        psutil_data = json.load(file(psutil_file))
        data = self.format_data(psutil_data)
        return data

    def format_data(self, psutil_data):
        data = []

        #
        # Load average
        #
        load = ' '.join(str(l) for l in psutil_data['Load average'])
        data.append(('Load average', load))

        #
        # Network
        #
        bytes_recv = psutil_data['Network']['eth0']['bytes_recv']
        bytes_sent = psutil_data['Network']['eth0']['bytes_sent']

        bytes_recv = humanize.naturalsize(bytes_recv, gnu=True)
        bytes_sent = humanize.naturalsize(bytes_sent, gnu=True)

        data.append(('Network',
                     (('Bytes sent', bytes_sent),
                      ('Bytes received', bytes_recv))))

        #
        # Swap memory
        #
        swap_perc = psutil_data['Swap memory']['percent']
        sin = psutil_data['Swap memory']['sin']
        sout = psutil_data['Swap memory']['sout']

        swap = (('% used (best: 0.0)', swap_perc),
                ('Pages per second (out) (best: 0)', sin),
                ('Pages per second (in)  (best: 0)', sout),)
        data.append(('Swap memory', swap))
        return data

    def get_output_name(self):
        return 'Operating System information'
